BIN_ID=2
BIN_NAME="CAS BASURA"

RECYCLABLE = 1
NON_RECYCLABLE = 2

TRIG_RECYCLABLE_BIN = 15
ECHO_RECYCLABLE_BIN = 14

TRIG_NON_RECYCLABLE_BIN = 24
ECHO_NON_RECYCLABLE_BIN = 23

OBJECT_DETECTOR_PIN = 21

SERVO_PIN=18

INITIAL_DEPTH_CM = 75.0         # Initial depth of the bin in cm
THRESHOLD_PERCENTAGE = 85.0     # Threshold percentage

