BIN_ID=1
BIN_NAME="CAS BASURA"

RECYCLABLE = 1
NON_RECYCLABLE = 2

TRIG_RECYCLABLE_BIN = 15
ECHO_RECYCLABLE_BIN = 14

TRIG_NON_RECYCLABLE_BIN = 24
ECHO_NON_RECYCLABLE_BIN = 23

TRIG_DISTANCE_CHECKER = 24
ECHO_DISTANCE_CHECKER = 23

SERVO_PIN=18